openapi: 3.0.3
info:
  title: "Telegram Bot API - Webhook Integration"
  version: 1.0.0
servers:
  - url: "https://api.telegram.org"
    description: "Основной сервер телеграмм АПИ"
paths:
  /bot{token}/setWebhook:
    post:
      summary: set Webhook
      operationId: setWebhook
      tags:
        - Webhook
      parameters:
        - in: path
          name: token
          required: true
          description: "Токен телеграмм бота"
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BaseWebhook"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/WebhookWithCertificate"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
          description: Успешно установлен Webhook
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /bot{token}/deleteWebhook:
    delete:
      summary: delete Webhook
      operationId: deleteWebhook
      tags:
        - Webhook
      parameters:
        - in: path
          name: token
          required: true
          description: "Токен телеграмма"
          schema:
            type: string
        - in: query
          name: drop_pending_updates
          required: false
          description: "Передай True, чтобы сбросить все накопившиеся обновления"
          schema:
            type: boolean
            default: false
            example: true
      responses:
        "200":
          description: Успешно удален Webhook
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    BaseWebhook:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
          description: "Url сервера, на который тг будет отправлять обновления"
        ip_address:
          type: string
          description: "Ip-адрес сервера"
          format: ipv4
          example: "197.0.2.1"
        max_connections:
          type: integer
          description: "Количество одновременных подключений бота (default=40, max=100, min=1)"
          maximum: 100
          minimum: 1
          default: 40
        allowed_updates:
          type: array
          description: "Список обновлений, которые бот хочет получать. По дефолту и с пустым массивом получает все, кроме chat_member, message_reaction,message_reaction_count."
          items:
            type: string
          example:
            - "message"
            - "edited_channel_post"
            - "callback_query"
        drop_pending_updates:
          type: boolean
          description: "Сбрасывает копившиеся ранее обновления до момента запуска бота"
        secret_token:
          type: string
          description: "Секретный токен для авторизации запросов"
          maxLength: 256
          minLength: 1
          pattern: "^[A-Za-z0-9_-]+$"
    WebhookWithCertificate:
      allOf:
        - $ref: "#/components/schemas/BaseWebhook"
        - type: object
          properties:
            certificate:
              type: string
              format: binary
              description: "SSl сертификат сервера,передается в случае самоподписанного сертификата."
    Error:
      type: object
      required:
        - ok
        - error_code
        - description
      properties:
        ok:
          type: boolean
          example: false
        error_code:
          type: integer
        description:
          type: string
    Success:
      type: object
      required:
        - result
        - ok
      properties:
        result:
          type: boolean
        ok:
          type: boolean
        description:
          type: string
